name: Force sync master from apache/airflow
on:
  push:
jobs:
  repo-sync:
    if: github.repository != 'apache/airflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "apache/airflow"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
